apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mdnice
  name: mdnice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdnice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mdnice
    spec:
      containers:
      - image: weihanli/mdnice
        name: mdnice
        ports:
        - name: "web"
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            cpu: 30m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 16Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mdnice
  name: mdnice
spec:
  ports:
    - name: "web"
      port: 80
      targetPort: "web"
  selector:
    app: mdnice

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mdnice-ingress
spec:
  rules:
  - host: "mdnice.weihanli.top"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mdnice
            port:
              name: "web"
  tls:
  - hosts:
    - mdnice.weihanli.top