version: "3.4"

services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    restart: always
    ports: 
      - 9000:9000
    volumes:
      - ./config:/etc/v2ray
      # - ./config/config.json:/etc/v2ray/config.json
      # - ./config/config-websocket-no-tls.json:/etc/v2ray/config.json
