services:
  aspire-dashboard:
    container_name: aspire-dashboard
    image: weihanli/aspire-dashboard:9.4
    ports:
      - 18888:18888
      - 4317:18889
    environment:
      # Anonymous
      # DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
      # # OpenId Connect
      Authentication__Schemes__OpenIdConnect__Authority: "https://id.weihanli.xyz"
      Authentication__Schemes__OpenIdConnect__ClientId: "aspire"
      Authentication__Schemes__OpenIdConnect__ClientSecret: "1fcbbab8-1f64-9f91-8be6-92412570d1f6"
      Authentication__Schemes__OpenIdConnect__GetClaimsFromUserInfoEndpoint: "true"
      Dashboard__Frontend__AuthMode: "OpenIdConnect"
      Dashboard__Frontend__OpenIdConnect__RequiredClaimType: "role"
      Dashboard__Frontend__OpenIdConnect__RequiredClaimValue: "Aspire"
