services:
  aspire-dashboard:
    container_name: aspire-dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - 18888:18888
      - 4317:18889
    environment:
      # Anonymous
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: "true"
      # # OpenId Connect
      # Authentication__Schemes__OpenIdConnect__Authority: "https://id.weihanli.xyz"
      # Authentication__Schemes__OpenIdConnect__ClientId: "aspire"
      # Authentication__Schemes__OpenIdConnect__ClientSecret: ""
      # Authentication__Schemes__OpenIdConnect__GetClaimsFromUserInfoEndpoint: "true"
      # Authentication__Schemes__OpenIdConnect__Scope__0: "roles"
      # # Dashboard__Frontend__OpenIdConnect__RequiredClaimType: "role"
      # # Dashboard__Frontend__OpenIdConnect__RequiredClaimValue: "Aspire"
      # Dashboard__Frontend__AuthMode: "OpenIdConnect"
